### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by leoarmelin** [alexhiraga/catopedia#1]
Nice work! Here are some points to think about.

## next.config.ts
It's not a good practice to allow every hostname. [NextJS Docs](https://nextjs.org/docs/pages/api-reference/components/image#remotepatterns)
> To protect your application from malicious users, configuration is required in order to use external images.
```typescript
// next.config.ts
const nextConfig: NextConfig = {
  basePath: process.env.NEXT_PUBLIC_IS_PRODUCTION === 'true' ? '/catopedia' : '',
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
    ],
  }
};
```

## public/
It's preferred to place icons or images inside a folder, like `public/assets`.

## src/app
We usually only put files related to pages (with a few exceptions) inside the `src/app` folder. Components, models, assets, etc, are created on `src/` scope.

## src/app/types
Files are using `.tsx` extension but there's no HTML/React Component code on it. If there's no UI, you can use `.ts`.

## src/app/components
NextJS provides abstractions for `<Link>` tag. Usually it's better for performance/pre-fetching rather than `<a>`.

## src/app/cat/[id]
Probably the reason it's not working on production environment is the `generateStaticParams` function. There's no need for it to be here. Also, it doesn't works on dev env, that's why it worked before.
Try to use `useParams` or `useSearchParams` for it. Usually they are useful, sometimes not.

## React Contexts
They are useful, but they don't need to be at top-level in the application. Usually we split contexts in pages to reduce page loading time and javascript bundle size. And of course there are cases where the contexts will be global.

## HTML tags
There are some good HTML tags to use in some contexts.
- `<nav>` to indicate there's a navigation section
- `<aside>` to say a component is outside the main content
- `<form>` for structures like input + confirm button

**Comment by alexhiraga** [comment]
@leoarmelin Thanks for the feedback!

I've solved most of the issues you have mentioned, some was a little of a lack of experience using NextJS, others were just my fault 😁. 

About the src/app/cat/[id], I tried many ways to fix that, but every time I got a problem when building the project.
When I tried using "useParams", I have the error:
Error: Page "/cat/[id]" is missing "generateStaticParams()" so it cannot be used with "output: ***" config.

I tried using 'generateStaticParams()', the build run successfully but then I tried to reach /cat/someidhere and got the 404 error.

I also tried the 'useSearchParam' and the error was:
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/cat".
 Even though I used the <Suspense> wrap, it didn't work :(
 
 I will try to fix that to build my project in GH Pages so I can show my friends the Catopedia.
 
 Thanks!
